name: adv_vit_cnn
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pip
  - pip:
      - pytorch-lightning
      - hydra-core
      - tensorboard
      - wandb
      - torchattacks
      - deeplake
  - datasets
  - pillow
  - numpy
  - fsspec<=2024.3.1
